import "./globals.css";
import Navbar from "../components/navbar";
import { Providers } from "../components/providers";

export const metadata = {
  title: "Captionizer",
  description: "Generated by Ganesh Mangla",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body className="min-h-screen w-full text-black justify-center">
        <main>
          <Providers>
            <Navbar />
            {children}
          </Providers>
        </main>
      </body>
    </html>
  );
}
